# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Lillen Art
tagline: 'Art Creation & Tutorials'
description: 'Art Creation & Tutorials'
baseurl: /
author:
  name: 'Synthia Lillendandie'
  url: /
paginate: 5

# Custom vars
#version: 

# Locally building github page
hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Twitter
twitter:site: LillenArt

#Read More 
excerpt_separator: <!--more-->