on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          # Optional: specify npm as the package manager
          # npm: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
